Shippable/reqProc

boot.sh
https://github.com/Shippable/reqProc/issues/5
This makes the node.js app to startup
=> fix boot.sh to start nodejs app

_common/jobConsoleAdapter.js, _common/micro/MicroService.js, _common/micro/healthChecks/checkShippableApi.js, _common/micro/healthChecks/postNodeStats.js, _common/micro/healthChecks/updateNodeStatus.js, _common/micro/healthChecks/validateNode.js, _common/micro/healthChecks/validateService.js, microWorker.js
https://github.com/Shippable/reqProc/issues/6
We don't have `_global` anymore and the files needed from `_global` are moved to `_common` 
This PR updates all the references to the shippable adapter file which was in `_global` in case of `genExec`, but now moved to `_common`
=> corrects the path of shippable adapter

microWorker.js
https://github.com/Shippable/reqProc/issues/8
[buildJobConsoleAdapter.js](https://github.com/Shippable/reqProc/blob/master/_common/buildJobConsoleAdapter.js) was already moved from `_global` to `_common`. So updated it's reference.
=> fix buildConsoleAdapter path in microworker

_common/logging/logger.js, _common/micro/setupMS.js
https://github.com/Shippable/reqProc/issues/9
Moves `_global/logging/logger.js` to `_common/logging/logger.js` and updating the references.
=> fix logging reference

managed/runSh/run.sh, managed/runSh/runSh.js
https://github.com/Shippable/reqProc/issues/13
Adding this to make the build green. Right now, only a plain `runSh` job with following yml will be passing
```yml
- name: min-runsh
type: runSh
steps:
- TASK:
- script: echo "hello"
```
This will be removed in future PMs belonging to the current heap.
=> Adds runSh temporarily

_common/micro/setupMS.js, app.js
https://github.com/Shippable/reqProc/issues/36
When required ENVs are not found, the following logs appear in reqProc
If all the envs are non-empty, the reqProc is initialized successfully
=> checks for emptiness of dir envs

app.js
https://github.com/Shippable/reqProc/issues/37
If the envs point to a path that does not exist or a path that points to a file with same name, we get the following error logs
If the envs point to a valid directory, reqProc is initialized successfully.
=> checks if envs point to valid dir

_common/executeJobScript.js, workflows/ci.js
https://github.com/Shippable/reqProc/issues/97
This PR copies the same code of legacy ci from genExec to reqProc.
Was able to successfully run build on local.
Right now there is only one dependent script ( `_common/executeJobScript.js` ). We will move this to a more appropriate folder which will group the files that deal with legacy ci. ( Will do this process in the next issue or at the end, based on the upcoming changes )
=> moves legacy ci to ci workflow

job/handlers/resources/_common/ciRepo/outStep.js, runCI/resources/ciRepo/outStep.js
#236 
Tested a runSh job with a gitRepo input and ciRepo output.  A new ciRepo version was posted when the sourceNames matched, and not when they didn't.
=> #236; uses ciRepo sourceName from version.

job/scriptsGen/normalizeSteps.js, job/setupDependencies.js
https://github.com/Shippable/reqProc/issues/238
This PR generates envs as key-value objects instead of a formatted string which is specific to bash. This allows us to use the key-value as we like in `execTemplates` and do the formatting for each OS separately.
Verified on PowerShell ( Windows Server 2016 ) and bash ( Ubuntu 16.04 )
Test cases for Powershell
- Envs - https://github.com/sample-organisation/rc-cd/blob/master/x86-64/windows-server-2016/host/envs/shippable.jobs.yml
Test cases for bash 
- Envs - https://github.com/sample-organisation/rc-cd/blob/master/x86-64/ubuntu-16-04/host/envs/shippable.jobs.yml
- CliConfigs - https://github.com/sample-organisation/rc-cd/blob/master/x86-64/ubuntu-16-04/host/cliConfigs/shippable.jobs.yml
Please let me know if there are additional test cases …
=> Changes the format of envs 

runCI/scriptsGen/generateReplaceScript.js, runCI/scriptsGen/generateScriptFromTemplate.js, workflows/runCI.js
#246 
Copies the script templating files from runSh and updates `runCI.sh` to match genExec  and runSh.  Tested with a runCi job and the environment variable and version.json of the resource with a placeholder in `versionName` were correct.
=> #246; replaces resource placeholders in runCI.

job/handlers/resources/_common/cliConfig/inStep.js
https://github.com/Shippable/reqProc/issues/260
this fix is for ubuntu. For windows, this will be fixed after discussing with @scriptnull
=> escapes space in integration names in file path

workflows/runCI.js
#250 
Removes the double quotes surrounding double-quoted values to avoid repeating the quotes currently in the `envs` templates.
=> #250; avoids repeating quotes in the template.

job/postVersion.js
https://github.com/Shippable/reqProc/issues/274
Tested with
```yml
- name: x86-64-windows-server-2016-host-out-image-post
type: runSh
runtime:
architecture: x86_64
os: WindowsServer_2016
container: false
flags:
- x86-64
- windows-server-2016
- x86-64-windows-server-2016-host-out
steps:
- IN: x86-64-trigger
- IN: windows-server-2016-trigger
- OUT: master-image-1
overwrite: true
- TASK:
name: should-post-resource-state
script:
- gci env:*
- if ( "$env:MASTERIMAGE1_NAME" -ne "master-image-1" ) { Write-Error "incorrect env" }
- '"versionName=master.$env:BUILD_NUMBER" | Out-File -Encoding utf8 -FilePath $env:JOB_STATE\$env:MASTERIMAGE1_NAME.env -NoNewLine'
- name: x86-64-windows-server-2016-host-out-image-put
type: runSh
runtime:
architecture: x86_64
os: WindowsServer_2016
container: false …
```
=> Removes BOM character

job/handlers/resources/Ubuntu_14.04/gitRepo/inStep.js, job/handlers/resources/Ubuntu_16.04/gitRepo/inStep.js, job/handlers/resources/WindowsServer_2016/gitRepo/inStep.js, job/handlers/resources/macOS_10.12/gitRepo/inStep.js, job/initializeJob.js, runCI/resources/gitRepo/inStep.js, workflows/runCI.js
#280 
Updated to match genExec.  Tested runSh and runCI on Ubuntu 16.04 with no version and with no shaData.  The runCI job failed on an earlier error when the version did not exist (stating that there were no versions).
=> #280; updates error messages for missing gitRepo version or shaData.

build.ps1
https://github.com/Shippable/reqProc/issues/294
Adding `--no-cache` as we just have one windows node for building images and it is always using the cache and the latest code changes are not being reflected. So, making the build process to do a fresh build and push every time.
=> adds no cache option for windows docker build

job/setupDependencies.js, workflows/runCI.js
#297 
The same as for genExec.  This removes leading numbers from resource names when using them as environment variable names to create valid environment variables.  Tested with jobs and inputs starting with numbers in runCi and runSh.  Numbers that are not at the beginning of the name remain, and leading numbers are removed.
=> #297; removes leading numbers from generated variable names.

workflows/runCI.js
#324 
Tested with a new Digital Ocean installation.  Values containing an `=` failed before and will now work correctly.
=> #324; correctly parses environment variables containing =.

job/handlers/handleDependency.js, job/handlers/resources/Ubuntu_14.04/gitRepo/inStep.js, job/handlers/resources/Ubuntu_14.04/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/Ubuntu_14.04/gitRepo/templates/providers/_github.sh, job/handlers/resources/Ubuntu_14.04/gitRepo/templates/providers/_gitlab.sh, job/processINs.js, job/setupDependencies.js
**Note:** While the basic scenarios for public and privates projects have been tested for Github, Gitlab, and Bitbucket, this still needs extensive testing for all scenarios including pull requests, releases, tags etc. Also, the actual usage of the key itself needs to be tested. The [repo here](https://github.com/shriv-ra/fuzzy-system/blob/pm-10110/shippable.yml) covers the basic cases.
https://github.com/Shippable/reqProc/issues/326
=> Move PEM key path for gitRepo from /tmp to /build/secrets for Ubuntu 14.04

job/handlers/resources/CentOS_7/gitRepo/templates/inStep.sh, job/handlers/resources/Ubuntu_14.04/gitRepo/templates/inStep.sh, job/handlers/resources/Ubuntu_16.04/gitRepo/templates/inStep.sh, job/handlers/resources/macOS_10.12/gitRepo/templates/inStep.sh
As far as I can tell, these files are not used at all because we have specific handlers for Github/Github EE, Gitlab, Bitbucket/Bitbucket Server. I'm just copying over the contents just in case it gets used for something. Tested by commenting out the specific handlers.
https://github.com/Shippable/reqProc/issues/336
=> Update generic inStep.sh to save gitRepo PEM key in /build/secrets

image/x86_64/WindowsServer_2016/Dockerfile
For #338 
GitHub's recent TLS upgrades causes our downloads to fail because PowerShell still tries TLS 1.0 by default:
```
Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel.
At line:1 char:1
+ Invoke-WebRequest https://github.com/Shippable/execTemplates/archive/ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```
This change forces it to use 1.2 for the current session.
=> Force TLS 1.2 for GitHub downloads on Windows

job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_bitbucket.ps1, job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_github.ps1, job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_gitlab.ps1
For https://github.com/Shippable/reqProc/issues/338
For https://github.com/Shippable/reqProc/issues/339
For https://github.com/Shippable/reqProc/issues/340
Going back to copy-item because something is preventing move from working. I keep getting access denied, which usually means something is locking the file. Seems like a timing issue, but I didn't want to try adding sleep to fix it.
Addressing multiple issues in one shot because it's the same change and it'll save be 30 minutes on each build.
=> Back to Copy-Item -Force to preserve the git directory on Windows

workflows/runCI.js
https://github.com/Shippable/micro/issues/6621
Verified following scenarios:
- If `replicateOnPullRequest` is **set to true** then on pullRequest new versions for replicate resource is getting pushed.
- If `replicateOnPullRequest` is **not available** then on pullRequest new versions for replicate resource is getting pushed.
- If `replicateOnPullRequest` is **set to false** then on pullRequest new versions for replicate resource is **not** getting pushed.
=> posts new replicate version only if replicateOnPullRequest is set to true in case of pull requests

_common/micro/setupMS.js, app.js, workflows/runCI.js
#380 
Makes `SHIPPABLE_AMI_VERSION` an available environment variable in CI.  Tested by updating a custom node in RC.
=> #380; adds SHIPPABLE_AMI_VERSION.

job/setupDependencies.js
#382 
Checked that the value is available in a runSh job.
=> #382; adds SHIPPABLE_AMI_VERSION to runSh.

_common/parseSecureVariable.js, job/setupDependencies.js, workflows/runCI.js
#384 
Allows spaces (escaped or quoted) and multiple `=` in secure environment variables.  The same as genExec.
=> #384; updates secure params parsing.

job/getPreviousState.js, job/handlers/resources/_common/state/inStep.js, job/handlers/resources/_common/state/outStep.js, job/handlers/saveState.js, job/setupDependencies.js, runCI/getPreviousState.js, runCI/resources/state/inStep.js, runCI/resources/state/outStep.js, runCI/saveState.js, workflows/runCI.js
#414
Tests:
1. Tested that previous(the ones which are not base64 encoded) state files are being saved correctly and their content is not base64 decoded.
2. Tested that state files with binary data are being saved and used correctly in IN jobs and their `sha1sum` matches
3. Tested that runCI jobs having IN and OUT to state resource are running fine, where we are updating state resource files.
4. Tested that runSh jobs having IN and OUT to state resource are running fine, where we are updating state resource files
5. Tested that for runSh and runCI jobs, previous state(state files) is being saved correctly
6. Tested that for runSh and runCI IN dependency jobs state is state(files) is being saved correctly
=> update reqProc to encode state files to base64 and decode from base64

job/setupDependencies.js, workflows/runCI.js, workflows/runSh.js
#444
#445
setUpDependencies.js handler is only called in the runSh flow (runCI has its own function and does not use the separate handler) so i did not need to put conditions on the BUILD_URL variable. But i did have to put the WWW_URL in two places so that both jobs and buildJobs will have access to it.
in NF, the pipeline job URL is defined as:
```
buildUrl: global.systemConfig.wwwUrl + '/subscriptions/' +
bag.subscription.id + '/pipelines/builds/' + bag.buildJob.buildId +
'/consoles',
```
so that was also used here.
=> add SHIPPABLE_WWW_URL

shippable.yml
https://github.com/Shippable/pm/issues/11252
2 windows reqProc images are built every time a change is made to reqProc. It should only built if `reqProc_runCI` job is successfuly completed
=> do not trigger reqProc build on change to reqProc repo

job/setupDependencies.js, workflows/runCI.js
#477 
Logs the error and continues when a job input doesn't have state.  The state files will not be available but the current job will run.
=> #477; allows job inputs without state.
