_common/micro/healthChecks/updateNodeStatus.js, _common/statusCodes.js
https://github.com/Shippable/reqProc/issues/7
This PR moves the `statusCodes.js` file from `_global` to `_common` and fixes all it's references.
=> fixes status code

_common/handleErrors/ActErr.js, _common/micro/setupMS.js
https://github.com/Shippable/reqProc/issues/10
Moving ActErr.js from `_global` to `_common`
=> adds ActErr and updates it reference

build.sh
https://github.com/Shippable/reqProc/issues/30
=> Fix incorrect path and image name

Dockerfile, boot.sh
https://github.com/Shippable/reqProc/issues/38
When REQEXEC_SRC_DIR does not point to a valid directory
When the expected directories are present, copying and booting of app happens correctly
=> copies reqExec from src to dest

microWorker.js
https://github.com/Shippable/reqProc/issues/39
https://github.com/Shippable/reqProc/issues/40
When everything passes
Following failures are caused by setting `err` object to true explicitly ( for taking these screenshots )
When creating a dir fails
When creating a file fails
When cleanup fails
=> creates dir structure and cleans build dir

_common/micro/healthChecks/validateNode.js, _common/micro/setupMS.js, app.js, microWorker.js
https://github.com/Shippable/reqProc/issues/45
=> Obtain reqProc container name from ENV

_common/micro/setupMS.js, app.js, boot.sh
https://github.com/Shippable/reqProc/issues/47
=> Copy reqExec binary using BIN env

_common/example/steps.json, microWorker.js
https://github.com/Shippable/reqProc/issues/49
https://github.com/Shippable/reqProc/issues/54
=> saves job steps

_common/example/steps.json
https://github.com/Shippable/reqProc/issues/61
=> Update the example

microWorker.js
closes https://github.com/Shippable/reqProc/issues/64
=> set job envs

job/cleanup.js, job/generateSteps.js, job/handoffAndPoll.js, job/readJobStatus.js, job/updateStatus.js, microWorker.js
closes https://github.com/Shippable/reqProc/issues/59
=> move code out of microworker

job/cleanup.js, job/getPreviousState.js, job/getSecrets.js, job/initJob.js, job/setupDependencies.js, job/setupDirs.js, microWorker.js
closes https://github.com/Shippable/reqProc/issues/70
closes https://github.com/Shippable/reqProc/issues/71
closes https://github.com/Shippable/reqProc/issues/72
closes https://github.com/Shippable/reqProc/issues/73
=> adds job init logic

job/handlers/executeDependencyScript.js, job/handlers/executeScript.js, job/handlers/handleDependency.js, job/handlers/resources/ciRepo/outStep.js, job/handlers/resources/dockerOptions/inStep.js, job/handlers/resources/gitRepo/inStep.js, job/handlers/resources/gitRepo/templates/inStep.sh, job/handlers/resources/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/gitRepo/templates/providers/_github.sh, job/handlers/resources/gitRepo/templates/providers/_gitlab.sh, job/handlers/resources/params/inStep.js, job/handlers/resources/state/inStep.js, job/handlers/resources/state/outStep.js, job/handlers/resources/syncRepo/inStep.js, job/handlers/resources/syncRepo/templates/inStep.sh, job/handlers/resources/syncRepo/templates/providers/_bitbucket.sh, job/handlers/resources/syncRepo/templates/providers/_github.sh, job/handlers/resources/syncRepo/templates/providers/_gitlab.sh, job/processINs.js, job/setupDependencies.js, microWorker.js
closes https://github.com/Shippable/reqProc/issues/74
this PR just copies the logic as is. Moving scripts to execTemplates will be done in a later PR.
=> process IN dependencies

_common/example/scripts/h_task_1.sh, _common/example/steps.json, job/generateSteps.js
https://github.com/Shippable/reqProc/issues/61
=> Update example and copy scripts

_common/normalizeSteps.js
=> add helper function in reqProc to convert old runSh steps to new format

_common/micro/setupMS.js, job/generateSteps.js, job/scriptsGen/generateScript.js, job/scriptsGen/generateScriptFromTemplate.js, job/scriptsGen/normalizeStepsV1.js, job/scriptsGen/normalizeStepsV2.js
closes https://github.com/Shippable/reqProc/issues/81
closes https://github.com/Shippable/reqProc/issues/82
closes https://github.com/Shippable/reqProc/issues/83
=> creates script to run on host

job/scriptsGen/normalizeStepsV2.js
https://github.com/Shippable/reqProc/issues/85
=>  Normalize the runSh options

job/generateSteps.js, job/scriptsGen/generateScript.js, job/scriptsGen/normalizeStepsV2.js
closes https://github.com/Shippable/reqProc/issues/87
=> create docker script from template

job/generateSteps.js, job/readJobStatus.js, job/scriptsGen/generateScript.js, job/setupDependencies.js, job/updateStatus.js, microWorker.js
closes https://github.com/Shippable/reqProc/issues/89
=> export envs in builds

job/generateSteps.js
https://github.com/Shippable/pm/issues/9261
=> Add a couple of ENVs

_common/jobConsoleAdapter.js, job/initJob.js, job/updateStatus.js, microWorker.js, workflows/ci.js, workflows/runCI.js, workflows/runSh.js
https://github.com/Shippable/reqProc/issues/95
https://github.com/Shippable/reqProc/issues/96
This PR only modifies the organisation of the code. Tested this by running sample runSh job. It continues to behave the same.
=> creates workflows and moves runSh

job/createTrace.js, job/handlers/saveState.js, job/persistPreviousState.js, job/postVersion.js, job/processINs.js, job/processOUTs.js, job/saveStepState.js, job/setupDirs.js, job/updateStatus.js, workflows/runSh.js
closes https://github.com/Shippable/reqProc/issues/75
this PR also creates OUT versions, trace
=> OUT handling

job/readJobStatus.js, workflows/runSh.js
https://github.com/Shippable/reqProc/issues/75
=> closes read job status grp

job/generateSteps.js, job/scriptsGen/generateScript.js, job/scriptsGen/generateScriptFromTemplate.js, job/setupDependencies.js
https://github.com/Shippable/reqProc/issues/90
=> Add init and clean up scripts for resources

job/scriptsGen/generateScript.js
https://github.com/Shippable/reqProc/issues/106
=> Rename container.sh to boot.sh

job/scriptsGen/generateScript.js
https://github.com/Shippable/reqProc/issues/108
=> Add a boot.sh for host

_common/micro/MicroService.js, _common/micro/healthChecks/validateNode.js, _common/micro/setupMS.js, job/setupDirs.js, microWorker.js, workflows/runSh.js
Plus, remove some more isServiceNode references
https://github.com/Shippable/reqProc/issues/111
https://github.com/Shippable/reqProc/issues/110
=> Skip clusterNode validation for runSh jobs

_common/micro/setupMS.js, job/pollBuildJobStatus.js, workflows/runSh.js
https://github.com/Shippable/reqProc/issues/113
=> Add a build job status poller

job/generateSteps.js, job/scriptsGen/generateKillScript.js, job/scriptsGen/generateScript.js, job/setupDirs.js
https://github.com/Shippable/reqProc/issues/114
=> Generate kill script

job/pollBuildJobStatus.js, job/readJobStatus.js
https://github.com/Shippable/reqProc/issues/114
=> Use job status name instead of code

job/scriptsGen/generateScript.js, job/scriptsGen/normalizeSteps.js
closes https://github.com/Shippable/reqProc/issues/126
closes https://github.com/Shippable/reqProc/issues/124
tested for following envs
```
options:
- env1: value1
env2: value2
- env3: value3
```
```
options:
env1: value1
env2: value2
```
```
options:
- env1: value1
- env2: value2
```
=> export TASK envs

_common/getStatusCodeByName.js, job/getSecrets.js, job/initJob.js, job/persistPreviousState.js, job/pollBuildJobStatus.js, job/postVersion.js, workflows/runSh.js
https://github.com/Shippable/reqProc/issues/132
=> removes isCI and uses new getStatusCodeByName

job/scriptsGen/generateScript.js, job/scriptsGen/normalizeSteps.js
https://github.com/Shippable/reqProc/issues/127
https://github.com/Shippable/reqProc/issues/128
https://github.com/Shippable/reqProc/issues/129
https://github.com/Shippable/reqProc/issues/125
=> adds container options

job/scriptsGen/generateScript.js, job/scriptsGen/normalizeSteps.js
https://github.com/Shippable/reqProc/issues/125
=> pull image, boolean

job/scriptsGen/generateScript.js
closes https://github.com/Shippable/reqProc/issues/136
=> add script helpers

job/notifyOnStart.js, job/pollBuildJobStatus.js, workflows/runSh.js
https://github.com/Shippable/reqProc/issues/138
=> Queue on_start notifications

job/generateSteps.js, job/scriptsGen/generateScript.js, job/scriptsGen/normalizeSteps.js
https://github.com/Shippable/reqProc/issues/140
=> Add handling of on_success, on_failure, always groups

_common/micro/setupMS.js, app.js, job/scriptsGen/normalizeSteps.js
=> Switch default image based on architecture

job/scriptsGen/normalizeSteps.js
https://github.com/Shippable/reqProc/issues/144
=> Add ENVs for Node OS, Architecture

job/handlers/resources/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/gitRepo/templates/providers/_github.sh, job/handlers/resources/gitRepo/templates/providers/_gitlab.sh, job/setupDependencies.js
https://github.com/Shippable/reqProc/issues/146,
https://github.com/Shippable/reqProc/issues/147,
https://github.com/Shippable/reqProc/issues/148,
https://github.com/Shippable/reqProc/issues/149
=> enhance grisham items for IS_PULL_REQUEST_CLOSE env

job/handlers/resources/image/inStep.js, job/handlers/resources/image/templates/inStep.sh
https://github.com/Shippable/reqProc/issues/151
=> add new handler for image

job/handlers/resources/cliConfig/inStep.js, job/scriptsGen/generateScript.js, job/setupDependencies.js
closes https://github.com/Shippable/reqProc/issues/156
this also has changes made in the comments of this [PR](https://github.com/Shippable/reqProc/pull/158)
=> cleans up cliConfig dependency handling

job/handlers/resources/cliConfig/inStep.js
https://github.com/Shippable/reqProc/issues/154
=> removes making script files executable, since it is already executable

_common/micro/setupMS.js, app.js, job/scriptsGen/generateScript.js
https://github.com/Shippable/reqProc/issues/164
=> Use task container command from env

job/scriptsGen/normalizeSteps.js
https://github.com/Shippable/reqProc/issues/166
=> Clone options and env

job/generateSteps.js, job/scriptsGen/generateScript.js, job/scriptsGen/normalizeSteps.js, job/setupDependencies.js
closes https://github.com/Shippable/reqProc/issues/171
closes https://github.com/Shippable/reqProc/issues/172
closes https://github.com/Shippable/reqProc/issues/174
=> do not use templates for anything other than scripts

job/getPreviousState.js, workflows/runSh.js
https://github.com/Shippable/reqProc/issues/168
- ran a runSh job with:
**when reset is true**
**when reset is false**
=> skips previous state function if reset is true

job/generateSteps.js, job/handoffAndPoll.js, job/scriptsGen/generateScript.js, job/scriptsGen/normalizeSteps.js, workflows/runSh.js
closes https://github.com/Shippable/reqProc/issues/176
closes https://github.com/Shippable/reqProc/issues/177
closes https://github.com/Shippable/reqProc/issues/178
=> update handoff and poll logic to support multiple handoffs

job/scriptsGen/normalizeSteps.js
https://github.com/Shippable/reqProc/issues/180
=> rejects job level options

Dockerfile, _common/micro/setupMS.js, app.js, boot.sh, build.sh, job/generateSteps.js, job/handlers/resources/cliConfig/inStep.js, job/scriptsGen/generateScript.js
https://github.com/Shippable/reqProc/issues/182
=> Save reqExec in Architecture/OS dependent path

Dockerfile
Incorrectly replaced this while testing.
https://github.com/Shippable/reqProc/issues/182
=> Fix Dockerfile placeholders

_common/logging/logger.js, job/generateSteps.js, job/getPreviousState.js, job/handlers/resources/gitRepo/inStep.js, job/handlers/resources/state/inStep.js, job/handlers/resources/state/outStep.js, job/handlers/saveState.js, job/pollBuildJobStatus.js, job/postVersion.js, job/readJobStatus.js, job/setupDependencies.js, job/setupDirectories.js, runCI/getPreviousState.js, runCI/resources/gitRepo/inStep.js, runCI/resources/state/inStep.js, runCI/resources/state/outStep.js, runCI/saveState.js, workflows/runCI.js, workflows/runSh.js
closes https://github.com/Shippable/reqProc/issues/185
=> use path.join

job/handlers/handleDependency.js, job/handlers/resources/ciRepo/outStep.js, job/handlers/resources/state/outStep.js
closes https://github.com/Shippable/reqProc/issues/187
=> use inDependency instead of rawMessage

build.sh, image/aarch64/Ubuntu_16.04/Dockerfile, image/x86_64/Ubuntu_16.04/Dockerfile
=> Manage Dockerfiles on Arch/OS basis

image/x86_64/WindowsServer_2016/Dockerfile, image/x86_64/macOS_10.12/Dockerfile
https://github.com/Shippable/reqProc/issues/191
=> Add Dockerfile for macOS

_common/micro/setupMS.js
https://github.com/Shippable/reqProc/issues/193
=> Use OS specific execTemplates

job/setupDependencies.js
https://github.com/Shippable/reqProc/issues/195
=> Update permissions on the right file

job/scriptsGen/normalizeSteps.js
https://github.com/Shippable/reqProc/issues/199
=> makes mac builds to run on host by default

boot.ps1, image/x86_64/WindowsServer_2016/Dockerfile, image/x86_64/WindowsServer_2016/install_node.ps1, image/x86_64/WindowsServer_2016/install_util.ps1, image/x86_64/WindowsServer_2016/util.ps1
https://github.com/Shippable/reqProc/issues/197
=> adds new docker file and boot.ps1 file

image/x86_64/WindowsServer_2016/Dockerfile
https://github.com/Shippable/reqProc/issues/197
=> fix code comment

image/aarch64/Ubuntu_16.04/Dockerfile, image/x86_64/Ubuntu_16.04/Dockerfile, image/x86_64/macOS_10.12/Dockerfile
https://github.com/Shippable/pm/issues/9622
https://github.com/Shippable/pm/issues/9623
https://github.com/Shippable/pm/issues/9624
=> Pull macOS reqExec binary in reqProc images

build.sh
https://github.com/Shippable/pm/issues/9622
https://github.com/Shippable/pm/issues/9623
https://github.com/Shippable/pm/issues/9624
=> Fix sed on macOS

job/scriptsGen/normalizeSteps.js
Also, cleans up and annotates normalizer.
Tested here: https://github.com/shriv-ra/pipelines/tree/grisham/normalizer
https://github.com/Shippable/reqProc/issues/205
=> Fix options getting applied twice

job/scriptsGen/normalizeSteps.js
https://github.com/Shippable/reqProc/issues/205
=> Fix incorrect variable

job/cleanup.js, workflows/runSh.js
https://github.com/Shippable/reqProc/issues/208
=> fixes build should error if /build directory cannot be cleaned

image/x86_64/WindowsServer_2016/Dockerfile
https://github.com/Shippable/reqProc/issues/213
tested locally by building reqproc image commenting out npm install sections
=> pull reqExec binaries from S3

job/generateNodeInfoSteps.js, job/handlers/executeScript.js, job/scriptsGen/generateNodeInfoScript.js, workflows/runSh.js
https://github.com/Shippable/reqProc/issues/215
Success
Failure
=> updates runSh workflow to use node info scripts for each workflow

image/x86_64/Ubuntu_16.04/Dockerfile, image/x86_64/macOS_10.12/Dockerfile
https://github.com/Shippable/reqProc/issues/219
=> adds reqExec binaries for Ubuntu 14.04 to reqProc

image/x86_64/Ubuntu_16.04/Dockerfile, image/x86_64/macOS_10.12/Dockerfile
https://github.com/Shippable/reqProc/issues/221
=> updates reqproc to pull reqExec binaries for CentOS_7

image/x86_64/WindowsServer_2016/Dockerfile
https://github.com/Shippable/reqProc/issues/217
=> Enhance Windows dockerfile

_common/micro/setupMS.js, job/handlers/executeScript.js, job/scriptsGen/generateNodeInfoScript.js, job/scriptsGen/generateScript.js, job/scriptsGen/normalizeSteps.js
https://github.com/Shippable/reqProc/issues/224
This results in the following output in my current dev setup
=> Uses powershell for windows

image/x86_64/WindowsServer_2016/Dockerfile
https://github.com/Shippable/reqProc/issues/225
=> unpacks execTemplates for windows correctly

job/postVersion.js, workflows/runCI.js
#230 
The same as genExec.  Tested by replicating repo resources in runCI and runSh.
=> #230; adds whitelist to repo replicate.

boot.ps1
https://github.com/Shippable/reqProc/issues/226
=> Copies reqExec from container to host runtime dir

job/setupDependencies.js, workflows/runCI.js
https://github.com/Shippable/reqProc/issues/233,
https://github.com/Shippable/reqProc/issues/234
=> update sourceName references in reqProc

job/scriptsGen/normalizeSteps.js
https://github.com/Shippable/reqProc/issues/240
=>  updates scriptsGen/normalizeSteps to support new script tags

job/pollBuildJobStatus.js
https://github.com/Shippable/reqProc/issues/242
=> UpdateS logic in buildJob status poller, to check whether buildJob has timed out

job/pollBuildJobStatus.js
https://github.com/Shippable/reqProc/pull/243
=> updates pollBuildJobStatus to remove redundancy

job/scriptsGen/generateReplaceScript.js, job/setupDependencies.js
#245 
Tested with runSh jobs on Ubuntu 14.04 and Centos 7.  Both environment variables and the version.json file (read through a shipctl command) have the replaced values.
=> #245; replaces placeholders in runSh.

workflows/runSh.js
https://github.com/Shippable/reqProc/issues/242
=> makes behavior of timeout jobs similar to cancelled

image/x86_64/WindowsServer_2016/Dockerfile
For https://github.com/Shippable/reqProc/issues/255
=> Install shipctl in reqProc for Windows

job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_github.ps1
https://github.com/Shippable/reqProc/issues/257
For PR with no conflicts
For PR with merge conflicts
=> handles pull requests for IN gitRepo in windows host runSh job 

job/handlers/resources/_common/cliConfig/inStep.js
=> Make inStep use platform specific script extensions

job/setupDependencies.js, job/setupDirectories.js
closes https://github.com/Shippable/reqProc/issues/264
closes https://github.com/Shippable/reqProc/issues/265
=> adds SHIPPABLE_INTEGRATION_ENVS_PATH env

job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_gitlab.ps1
https://github.com/Shippable/reqProc/issues/257
=> adds gitlab script for IN gitRepo

job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_bitbucket.ps1
https://github.com/Shippable/reqProc/issues/257
BB project: https://bitbucket.org/scriptnull/public
YML: 
https://github.com/sample-organisation/rc-cd/blob/aaa95bbbcffe4a7de09022660b329e2be502e404/x86-64/windows-server-2016/host/envs/shippable.jobs.yml#L94-L134
=> adds bitbucket IN gitrepo script

job/scriptsGen/generateScript.js, job/scriptsGen/normalizeSteps.js
https://github.com/Shippable/reqProc/issues/271
https://github.com/Shippable/reqProc/issues/272
=> adds kill_container script

job/generateSteps.js
https://github.com/Shippable/reqProc/issues/273
=> update steps to include killScript

_common/getStatusByCode.js, job/initializeJob.js, job/readJobStatus.js, job/updateStatus.js
https://github.com/Shippable/reqProc/issues/278
=> shows status name instead of code in logs

job/scriptsGen/normalizeSteps.js
https://github.com/Shippable/reqProc/issues/282
=> Make boot script extension platform specific

workflows/runSh.js
https://github.com/Shippable/reqProc/issues/285
=> closes grp for initialize job section in logs

job/handlers/resources/CentOS_7/gitRepo/inStep.js, job/handlers/resources/CentOS_7/gitRepo/templates/inStep.sh, job/handlers/resources/CentOS_7/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/CentOS_7/gitRepo/templates/providers/_github.sh, job/handlers/resources/CentOS_7/gitRepo/templates/providers/_gitlab.sh, job/handlers/resources/CentOS_7/syncRepo/inStep.js, job/handlers/resources/CentOS_7/syncRepo/templates/inStep.sh, job/handlers/resources/CentOS_7/syncRepo/templates/providers/_bitbucket.sh, job/handlers/resources/CentOS_7/syncRepo/templates/providers/_github.sh, job/handlers/resources/CentOS_7/syncRepo/templates/providers/_gitlab.sh
closes https://github.com/Shippable/reqProc/issues/287
closes https://github.com/Shippable/reqProc/issues/287=8
=> adds gitRepo && syncRepo resourceHandlers

job/handlers/executeDependencyScript.js, job/handlers/executeScript.js, job/setupDependencies.js
https://github.com/Shippable/reqProc/issues/284
https://rcapp.shippable.com/github/jatindogra/jobs/runSh-Job/builds/5a5c48021988770600af1e01/console
=> consolidate setup dependencies logs in one block

job/generateNodeInfoSteps.js, job/handlers/executeDependencyScript.js, job/handlers/executeScript.js, job/setupDependencies.js
https://github.com/Shippable/reqProc/issues/284
Sample Job
https://rcapp.shippable.com/github/jatindogra/jobs/runSh-Job/builds/5a5c691e10771a05000090ba/console
=> fixes job node info group

job/postVersion.js
=> remove circular references from OUT resources trace

build.ps1
https://github.com/Shippable/reqProc/issues/294
build.ps1 script will be called in `reqProc_x86_64_WindowsServer_2016_prep` job for building drydock/w16reqproc image.
=> adds build.ps1 script for building windows image

job/setupDependencies.js, workflows/runCI.js
https://github.com/Shippable/reqProc/issues/299
https://github.com/Shippable/reqProc/issues/300
___
Yml - https://github.com/jatindogra/sample-repo/blob/runsh/shippable.yml
___
runSh job - https://rcapp.shippable.com/github/jatindogra/jobs/runShJob/builds/5a603c5135c3ab050058ef46/console
___
runCI job - https://rcapp.shippable.com/github/jatindogra/sample-repo/runs/24/1/console
=> updates to not save envs for out param resource

job/generateSteps.js
https://github.com/Shippable/reqProc/issues/303
=> adds REQEXEC_SHELL job env

job/scriptsGen/generateScript.js, job/scriptsGen/normalizeSteps.js
https://github.com/Shippable/reqProc/issues/305
=> Use build.sh script for running container jobs for Linux

job/scriptsGen/generateScript.js, job/scriptsGen/normalizeSteps.js
https://github.com/Shippable/reqProc/issues/307
Verified with following builds
- https://rcapp.shippable.com/github/sample-organisation/jobs/x86-64-windows-server-2016-container-custom-img-multitask-multiple-valid/builds/5a705d832469ad0500458a74/console
- https://rcapp.shippable.com/github/sample-organisation/jobs/x86-64-windows-server-2016-container-custom-img-multiple-error/builds/5a705d962469ad0500458a75/console
- https://rcapp.shippable.com/github/sample-organisation/jobs/x86-64-windows-server-2016-container-custom-img-multiple-invalid/builds/5a705d9ad44ce7050041fd68/console
- https://rcapp.shippable.com/github/sample-organisation/jobs/x86-64-windows-server-2016-container-custom-img-invalid/builds/5a705da92469ad0500458a77/console
- …
=> generates build script for windows and macos

image/x86_64/WindowsServer_2016/install_node.ps1
https://github.com/Shippable/reqProc/issues/309
=> locks window-build-tools version

job/postVersion.js, job/updateStatus.js, workflows/runCI.js
=> update reqProc' s runCI and runSh handlers to save outData for OUT resources for which versions are posted

image/x86_64/WindowsServer_2016/Dockerfile
=> Use TAG in Windows Dockerfile

image/x86_64/WindowsServer_2016/Dockerfile, image/x86_64/WindowsServer_2016/install_node.ps1, image/x86_64/WindowsServer_2016/install_util.ps1
https://github.com/Shippable/reqProc/issues/313
=> installs openssh and sets required envs

job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_bitbucket.ps1, job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_gitlab.ps1
https://github.com/Shippable/reqProc/issues/314
Verified by running https://rcapp.shippable.com/github/sample-organisation/jobs/x86-64-windows-server-2016-host-envs-in-private-gitRepo/builds/5a7ab3048cadb6050009d675/console
=> Completes gitlab and bitbucket scripts

job/scriptsGen/normalizeSteps.js
https://github.com/Shippable/reqProc/issues/321
=> Copy proxy envs to task container if present

job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_github.ps1, job/handlers/resources/WindowsServer_2016/syncRepo/templates/providers/_github.ps1, job/handlers/resources/WindowsServer_2016/syncRepo/templates/providers/_gitlab.ps1
https://github.com/Shippable/reqProc/issues/315
https://github.com/Shippable/reqProc/issues/314
Verified by running
gitlab - https://rcapp.shippable.com/gitlab.com/scriptnull/jobs/gl-x86-64-windows-server-2016-host-envs-in-private-syncRepo/builds/5a7c335bf60e4c0500c61df0/console
=> completes private git cloning for gitlab and github

job/handlers/resources/CentOS_7/gitRepo/inStep.js, job/handlers/resources/CentOS_7/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/CentOS_7/gitRepo/templates/providers/_github.sh, job/handlers/resources/CentOS_7/gitRepo/templates/providers/_gitlab.sh
https://github.com/Shippable/reqProc/issues/328
=> Move PEM key path for gitRepo from /tmp to /build/secrets for CentOS 7

job/setupDependencies.js
https://github.com/Shippable/reqProc/issues/334
=> Export BUILD_SECRETS_DIR env

job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_github.ps1
=> Update Windows gitRepo template for github to use mv

job/handlers/resources/WindowsServer_2016/syncRepo/templates/providers/_bitbucket.ps1, job/handlers/resources/WindowsServer_2016/syncRepo/templates/providers/_github.ps1, job/handlers/resources/WindowsServer_2016/syncRepo/templates/providers/_gitlab.ps1
=> Use Copy-Item -Force for syncRepo clone in Windows

job/handlers/executeDependencyScript.js, job/handlers/handleDependency.js, job/handlers/resources/CentOS_7/gitRepo/inStep.js, job/handlers/resources/CentOS_7/syncRepo/inStep.js, job/handlers/resources/Ubuntu_14.04/gitRepo/inStep.js, job/handlers/resources/Ubuntu_14.04/syncRepo/inStep.js, job/handlers/resources/Ubuntu_16.04/gitRepo/inStep.js, job/handlers/resources/Ubuntu_16.04/syncRepo/inStep.js, job/handlers/resources/WindowsServer_2016/gitRepo/inStep.js, job/handlers/resources/WindowsServer_2016/syncRepo/inStep.js, job/handlers/resources/_common/ciRepo/outStep.js, job/handlers/resources/_common/cliConfig/inStep.js, job/handlers/resources/_common/dockerOptions/inStep.js, job/handlers/resources/_common/params/inStep.js, job/handlers/resources/_common/state/inStep.js, job/handlers/resources/_common/state/outStep.js, job/handlers/resources/macOS_10.12/gitRepo/inStep.js, job/handlers/resources/macOS_10.12/syncRepo/inStep.js, job/postVersion.js, job/processINs.js, job/processOUTs.js, job/setupDependencies.js, workflows/runSh.js
https://github.com/Shippable/reqProc/issues/348
https://github.com/Shippable/reqProc/issues/349
Old Consoles- https://rcapp.shippable.com/github/jatindogra/jobs/runSh-Job/builds/5aa0e9ee66b9f3140087b7ba/console
New Consoles- https://rcapp.shippable.com/github/jatindogra/jobs/runSh-Job/builds/5aa14d842a449a1700efffca/console
https://rcapp.shippable.com/github/jatindogra/jobs/runSh-Job-Out/builds/5aa14d872a449a1700efffcb/console
=> consolidate logs in the runSh workflow into a smaller number of parent groups

job/initializeJob.js, workflows/runCI.js
#351
1. CI timeout
2. runSh timeout
=> update reqProc to log timeouts for pipeline runSh buildJobs and CI jobs

job/handlers/resources/_common/state/inStep.js, runCI/executeDependencyScript.js, runCI/executeScript.js, runCI/resources/ciRepo/outStep.js, runCI/resources/dockerOptions/inStep.js, runCI/resources/gitRepo/inStep.js, runCI/resources/params/inStep.js, runCI/resources/state/inStep.js, runCI/resources/state/outStep.js, runCI/resources/syncRepo/inStep.js, runCI/saveState.js, workflows/runCI.js, workflows/runSh.js
https://github.com/Shippable/reqProc/issues/353
https://github.com/Shippable/reqProc/issues/354
Also fixed handling of closing of groups in runSh jobs
Sample runCI job-  https://rcapp.shippable.com/github/jatindogra/sample-repo/runs/71/1/console
=> Consolidate runCI logs into smaller parent groups

image/aarch64/Ubuntu_16.04/Dockerfile
=> new FROM aarch64 dockerfile

image/x86_64/Ubuntu_14.04/Dockerfile
=> add u14 and update u16

image/x86_64/Ubuntu_14.04/Dockerfile, image/x86_64/Ubuntu_16.04/Dockerfile, image/x86_64/macOS_10.12/Dockerfile, job/handlers/resources/RHEL_7/gitRepo/inStep.js, job/handlers/resources/RHEL_7/gitRepo/templates/inStep.sh, job/handlers/resources/RHEL_7/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/RHEL_7/gitRepo/templates/providers/_github.sh, job/handlers/resources/RHEL_7/gitRepo/templates/providers/_gitlab.sh, job/handlers/resources/RHEL_7/syncRepo/inStep.js, job/handlers/resources/RHEL_7/syncRepo/templates/inStep.sh, job/handlers/resources/RHEL_7/syncRepo/templates/providers/_bitbucket.sh, job/handlers/resources/RHEL_7/syncRepo/templates/providers/_github.sh, job/handlers/resources/RHEL_7/syncRepo/templates/providers/_gitlab.sh
https://github.com/Shippable/reqProc/issues/364
=> adds scripts to run reqProc on RHEL

_common/micro/healthChecks/x86_64/RHEL_7/activeContainerCount.sh, _common/micro/healthChecks/x86_64/RHEL_7/totalContainerCount.sh
https://github.com/Shippable/reqProc/issues/364
=> adds missing healthCheck files for RHEL_7

_common/shippable/Adapter.js, job/generateSteps.js, job/getRuntimeTemplate.js, job/scriptsGen/normalizeSteps.js, workflows/runSh.js
#367 
Tested with both custom and system nodes.  The default image in the runtimeTemplate was used in both cases.
=> #367; uses default image in runtimeTemplate for runSh.

image/x86_64/Ubuntu_14.04/Dockerfile, image/x86_64/macOS_10.12/Dockerfile
=> build reqprocs from new microbase

workflows/runSh.js
https://github.com/Shippable/reqProc/issues/371
Sample Job - https://rcapp.shippable.com/github/jatindogra/jobs/runSh-Job/builds/5aa8aa5dcbdd8a07002f76dc/console
=> fixes consoles for setup section

job/scriptsGen/normalizeSteps.js
#373
tested by modifying live container on custom node.
=> use drydockTag instead of release

job/setupDependencies.js
https://github.com/Shippable/pm/issues/10418
success build link:
https://rcapp.shippable.com/github/ankul-shippable/jobs/executable/builds/5aaa4faf2516980600644ad9/console
=> do not get state files for externalCI

job/handlers/saveState.js
https://github.com/Shippable/reqProc/issues/392
=> updates job/handlers/saveState to use path instead of substring

job/handlers/resources/_common/state/outStep.js, runCI/resources/state/outStep.js, runCI/saveState.js
https://github.com/Shippable/reqProc/issues/393
=> updates use of path module instead of substring while saving state

image/aarch64/Ubuntu_16.04/Dockerfile
closes https://github.com/Shippable/reqProc/issues/396
=> use aarch64_u16microbase as base image

image/x86_64/WindowsServer_2016/install_node.ps1
https://github.com/Shippable/reqProc/issues/398
=> install nodejs 8.11.2

job/postVersion.js
https://github.com/Shippable/reqProc/issues/400
=> update reqproc to ensure resource versions are updated

workflows/runCI.js
https://github.com/Shippable/reqProc/issues/402
=> Update reqProc/runCI to ensure resource versions are updated.

_common/micro/checkHealth.js, _common/micro/healthChecks/postNodeStats.js, _common/micro/healthChecks/validateNode.js
https://github.com/Shippable/reqProc/issues/404
https://github.com/Shippable/reqProc/issues/405
=> post node stats before validating the node

_common/micro/healthChecks/aarch32/Ubuntu_16.04/activeContainerCount.sh, _common/micro/healthChecks/aarch32/Ubuntu_16.04/totalContainerCount.sh, image/aarch32/Ubuntu_16.04/Dockerfile
https://github.com/Shippable/reqProc/issues/379
=> add support for aarch32

shippable.yml
https://github.com/Shippable/reqProc/issues/410
https://github.com/Shippable/reqProc/issues/411
=> adds jobs to build & tag aarch32_u16reqproc image

job/getPreviousState.js, job/handlers/resources/_common/state/inStep.js, job/setupDependencies.js, runCI/getPreviousState.js, runCI/resources/state/inStep.js, workflows/runCI.js
=> use same buffer for decoding base64 files

_common/handleErrors/ActErr.js, job/getPreviousState.js, job/handlers/resources/_common/state/inStep.js, job/handlers/resources/_common/state/outStep.js, job/handlers/saveState.js, job/scriptsGen/normalizeSteps.js, job/setupDependencies.js, runCI/getPreviousState.js, runCI/resources/state/inStep.js, runCI/resources/state/outStep.js, runCI/saveState.js, workflows/runCI.js
#413 
Continues instead of failing when there is no state system integration.
=> #413; allows some jobs to run without a state integration.

_common/micro/setupMS.js, app.js
https://github.com/Shippable/reqProc/issues/419
=> set clusterTypeCode & isRestrictedNode globally

job/initializeJob.js, workflows/runSh.js
https://github.com/Shippable/reqProc/issues/420
=> updates reqproc to skip build on host builds and docker options for restricted node pools

job/initializeJob.js
https://github.com/Shippable/reqProc/issues/422
=> do not allow private gitRepo INs for restricted nodepool

boot.sh, workflows/runCI.js
https://github.com/Shippable/pm/issues/11093
=> updates boot.sh to cleanup tmp directory

job/initializeJob.js, workflows/runCI.js
closes https://github.com/Shippable/reqProc/issues/425
=> private gitRepo as IN runCI job should fail on restricted nodepool

job/handlers/handleDependency.js
https://github.com/Shippable/pm/issues/11092
=> set subscription private key path

job/initializeJob.js
fixes https://github.com/Shippable/reqProc/issues/429
=> checks if container option is present in yml, before checking for host build

image/x86_64/WindowsServer_2016/install_node.ps1
https://github.com/Shippable/reqProc/issues/431
=> update nodejs to 8.11.3

job/setupDependencies.js, workflows/runSh.js
#6957
```
jobs:
- name: direct_integrations
type: runSh
runtime:
nodePool: shared_one
integrations:
- docker-subint
- key-value-subint
- ssh-subint
- nodes-subint
steps:
- IN: nginx-image
- IN: manifest-job
- TASK:
script:
- apt-get install tree
- tree $JOB_PATH          
- printenv
- GIT_SSH_COMMAND='ssh -i $SSHSUBINT_PRIVATE_KEY_PATH' git clone git@github.com:ankul-shippable/sample_node.git && ls
```
```
tree $JOB_PATH
/var/lib/shippable/26d3bbfe-bc86-41c4-b8da-b7cb01cde765/build
|-- IN
|   |-- manifest-job
|   |   |-- ***
|   `-- nginx-image
|       |-- ***
|-- OUT
|-- integrations
|   |-- docker-subint
|   |   |-- integration.env
|   |   `-- integration.json
|   |-- key-value-subint
|   |   |-- integration.env
|   |   `-- integration.json
|   |-- nodes-subint
|   |   |-- …
```
=> update reqProc to save data for runSh job direct integrations

job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_bitbucket.ps1, job/handlers/resources/WindowsServer_2016/syncRepo/templates/providers/_bitbucket.ps1
https://github.com/Shippable/reqProc/issues/434
private gitRepo PR build - https://rcapp.shippable.com/api.bitbucket.org/vishnushippable/jobs/min-sh/builds/5b5b082db436990800ffff65/console is correctly logging the contents of PR.
=> Updates bitbucket script for gitRepo and syncRepo

job/setupDependencies.js, workflows/runCI.js
=> update reqProc to not get accountIntegrations for shared subscription integrations

job/setupDependencies.js
https://github.com/Shippable/reqProc/issues/452
The job that triggered this job is named as `temp`
=> adds JOB_TRIGGERED_BY_USER env

job/handlers/resources/CentOS_7/gitRepo/inStep.js, job/handlers/resources/CentOS_7/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/CentOS_7/gitRepo/templates/providers/_github.sh, job/handlers/resources/CentOS_7/gitRepo/templates/providers/_gitlab.sh, job/handlers/resources/RHEL_7/gitRepo/inStep.js, job/handlers/resources/RHEL_7/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/RHEL_7/gitRepo/templates/providers/_github.sh, job/handlers/resources/RHEL_7/gitRepo/templates/providers/_gitlab.sh, job/handlers/resources/Ubuntu_14.04/gitRepo/inStep.js, job/handlers/resources/Ubuntu_14.04/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/Ubuntu_14.04/gitRepo/templates/providers/_github.sh, job/handlers/resources/Ubuntu_14.04/gitRepo/templates/providers/_gitlab.sh, job/handlers/resources/Ubuntu_16.04/gitRepo/inStep.js, job/handlers/resources/Ubuntu_16.04/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/Ubuntu_16.04/gitRepo/templates/providers/_github.sh, job/handlers/resources/Ubuntu_16.04/gitRepo/templates/providers/_gitlab.sh, job/handlers/resources/macOS_10.12/gitRepo/inStep.js, job/handlers/resources/macOS_10.12/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/macOS_10.12/gitRepo/templates/providers/_github.sh, job/handlers/resources/macOS_10.12/gitRepo/templates/providers/_gitlab.sh, runCI/resources/gitRepo/inStep.js, runCI/resources/gitRepo/templates/providers/_bitbucket.sh, runCI/resources/gitRepo/templates/providers/_github.sh, runCI/resources/gitRepo/templates/providers/_gitlab.sh
https://github.com/Shippable/reqProc/issues/447
https://github.com/Shippable/reqProc/issues/448
https://github.com/Shippable/reqProc/issues/449
https://github.com/Shippable/reqProc/issues/450
=> adds support for depth & gitConfig in bash scripts

job/handlers/resources/WindowsServer_2016/gitRepo/inStep.js, job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_bitbucket.ps1, job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_github.ps1, job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_gitlab.ps1
https://github.com/Shippable/reqProc/issues/447
https://github.com/Shippable/reqProc/issues/448
https://github.com/Shippable/reqProc/issues/449
https://github.com/Shippable/reqProc/issues/450
=> adds support for depth & gitConfig in ps1 scripts for gitRepo

job/handlers/resources/CentOS_7/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/RHEL_7/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/Ubuntu_14.04/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/Ubuntu_16.04/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/macOS_10.12/gitRepo/templates/providers/_bitbucket.sh, runCI/resources/gitRepo/templates/providers/_bitbucket.sh
https://github.com/Shippable/reqProc/issues/449
Since we reset --hard to the PR commit, HEAD will have the list of commits
=> check HEAD to see whether commit is present, in bitbucket PR builds

job/handlers/resources/CentOS_7/gitRepo/inStep.js, job/handlers/resources/RHEL_7/gitRepo/inStep.js, job/handlers/resources/Ubuntu_14.04/gitRepo/inStep.js, job/handlers/resources/Ubuntu_16.04/gitRepo/inStep.js, job/handlers/resources/WindowsServer_2016/gitRepo/inStep.js, job/handlers/resources/macOS_10.12/gitRepo/inStep.js, runCI/resources/gitRepo/inStep.js
https://github.com/Shippable/reqProc/issues/450
=> check whether config is a string

runCI/resources/gitRepo/inStep.js
https://github.com/Shippable/reqProc/issues/457
=> initialize depth to an empty array

job/cleanup.js, job/scriptsGen/generateCleanupGitConfigScript.js
https://github.com/Shippable/reqProc/issues/462
=> clean up git configs before & after a runSh build

job/handlers/resources/Ubuntu_16.04/gitRepo/inStep.js, job/handlers/resources/Ubuntu_16.04/gitRepo/templates/providers/_gerrit.sh, job/handlers/resources/Ubuntu_16.04/syncRepo/inStep.js, job/handlers/resources/Ubuntu_16.04/syncRepo/templates/providers/_gerrit.sh
https://github.com/Shippable/reqProc/issues/460
- Verified by using following ymls
```
jobs:
- name: sample-job-A
type: runSh
steps:
- IN: sample-git-repo
- TASK:
- script: echo "This is some script new"
- script: echo "This is some more script"
- name: host_single_task-1
type: runSh
runtime:
container: false
steps:
- IN: sample-git-repo
- IN: TEST_newBranchX
- TASK:
- script: echo "This is on host"
- script: uname -a
resources:
- name: sample-git-repo
type: gitRepo
integration: gerritsubint
versionTemplate:
sourceName: TEST-2
```
NOTE:  Once this gets merged will add them for all the providers after testing.
=> adds gitSync scripts for syncRepo and gitRepo in gerrit

job/handlers/resources/CentOS_7/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/CentOS_7/gitRepo/templates/providers/_github.sh, job/handlers/resources/CentOS_7/gitRepo/templates/providers/_gitlab.sh, job/handlers/resources/RHEL_7/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/RHEL_7/gitRepo/templates/providers/_github.sh, job/handlers/resources/RHEL_7/gitRepo/templates/providers/_gitlab.sh, job/handlers/resources/Ubuntu_14.04/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/Ubuntu_14.04/gitRepo/templates/providers/_github.sh, job/handlers/resources/Ubuntu_14.04/gitRepo/templates/providers/_gitlab.sh, job/handlers/resources/Ubuntu_16.04/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/Ubuntu_16.04/gitRepo/templates/providers/_gerrit.sh, job/handlers/resources/Ubuntu_16.04/gitRepo/templates/providers/_github.sh, job/handlers/resources/Ubuntu_16.04/gitRepo/templates/providers/_gitlab.sh, job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_bitbucket.ps1, job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_github.ps1, job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_gitlab.ps1, job/handlers/resources/macOS_10.12/gitRepo/templates/providers/_bitbucket.sh, job/handlers/resources/macOS_10.12/gitRepo/templates/providers/_github.sh, job/handlers/resources/macOS_10.12/gitRepo/templates/providers/_gitlab.sh, runCI/resources/gitRepo/templates/providers/_bitbucket.sh, runCI/resources/gitRepo/templates/providers/_github.sh, runCI/resources/gitRepo/templates/providers/_gitlab.sh
https://github.com/Shippable/reqProc/issues/463
=> unset git configs from gitRepo, if set

runCI/executeCleanupGitConfigScript.js, workflows/ci.js, workflows/runCI.js
https://github.com/Shippable/reqProc/issues/467
https://github.com/Shippable/reqProc/issues/468
=>  cleans up gitConfigs in CI

workflows/runCI.js
https://github.com/Shippable/reqProc/issues/467
doing this will show the cleanup step in the logs
=> close cleanup grp after git config cleanup

job/handlers/resources/CentOS_7/gitRepo/inStep.js, job/handlers/resources/CentOS_7/gitRepo/templates/providers/_gerrit.sh, job/handlers/resources/CentOS_7/syncRepo/inStep.js, job/handlers/resources/CentOS_7/syncRepo/templates/providers/_gerrit.sh, job/handlers/resources/RHEL_7/gitRepo/inStep.js, job/handlers/resources/RHEL_7/gitRepo/templates/providers/_gerrit.sh, job/handlers/resources/RHEL_7/syncRepo/inStep.js, job/handlers/resources/RHEL_7/syncRepo/templates/providers/_gerrit.sh, job/handlers/resources/Ubuntu_14.04/gitRepo/inStep.js, job/handlers/resources/Ubuntu_14.04/gitRepo/templates/providers/_gerrit.sh, job/handlers/resources/Ubuntu_14.04/syncRepo/inStep.js, job/handlers/resources/Ubuntu_14.04/syncRepo/templates/providers/_gerrit.sh, job/handlers/resources/WindowsServer_2016/gitRepo/inStep.js, job/handlers/resources/WindowsServer_2016/gitRepo/templates/providers/_gerrit.ps1, job/handlers/resources/WindowsServer_2016/syncRepo/inStep.js, job/handlers/resources/WindowsServer_2016/syncRepo/templates/providers/_gerrit.ps1, job/handlers/resources/macOS_10.12/gitRepo/inStep.js, job/handlers/resources/macOS_10.12/gitRepo/templates/providers/_gerrit.sh, job/handlers/resources/macOS_10.12/syncRepo/inStep.js, job/handlers/resources/macOS_10.12/syncRepo/templates/providers/_gerrit.sh
https://github.com/Shippable/micro/issues/7082
=> adds gerrit template files for all the providers

job/handlers/resources/CentOS_7/gitRepo/templates/providers/_gerrit.sh, job/handlers/resources/RHEL_7/gitRepo/templates/providers/_gerrit.sh, job/handlers/resources/Ubuntu_14.04/gitRepo/templates/providers/_gerrit.sh, job/handlers/resources/Ubuntu_16.04/gitRepo/templates/providers/_gerrit.sh, job/handlers/resources/macOS_10.12/gitRepo/templates/providers/_gerrit.sh
https://github.com/Shippable/pm/issues/11305
=> update gerrit clone script for pr close event

workflows/runCI.js
#475
envs:
```
TEST_1_REPO_GERRIT_PROJECT=test_project
TEST_1_REPO_GERRIT_PORT=29418
TEST_1_REPO_GERRIT_PATCHSET_UPLOADER_EMAIL=ankul@shippable.com
TEST_1_REPO_GERRIT_PATCHSET_UPLOADER_NAME=ankul
TEST_1_REPO_GERRIT_CHANGE_OWNER_EMAIL=undefined
TEST_1_REPO_GERRIT_REFSPEC=
TEST_1_REPO_GERRIT_PATCHSET_UPLOADER="ankul" <ankul@shippable.com>
TEST_1_REPO_GERRIT_REST_URL=http://18.237.132.38:8080
TEST_1_REPO_GERRIT_CHANGE_OWNER_NAME=undefined
TEST_1_REPO_GERRIT_CHANGE_UPLOADER_EMAIL=ankul@shippable.com
TEST_1_REPO_GERRIT_CHANGE_OWNER="undefined" <undefined>
TEST_1_REPO_GERRIT_CHANGE_SUBJECT=null
TEST_1_REPO_GERRIT_CHANGE_ID=null
TEST_1_REPO_GERRIT_HOST=18.237.132.38
TEST_1_REPO_GERRIT_PATCHSET_NUMBER=null
TEST_1_REPO_GERRIT_CHANGE_NUMBER=null
TEST_1_REPO_GERRIT_CHANGE_UPLOADER="ankul" …
```
=> update reqProc/workflows/runCI.js to expose gerrit specific envs for IN gitRepo resources 

job/persistPreviousState.js
#481 
Removes any new state files when the previous state is to be copied.
=> #481; removes new state when copying previous.

workflows/runCI.js
#483 
The same as genExec (except log grouping).  Any new files in the job state are removed when copying the previous state.
=> #483; removes new state when copying previous.
